use settings instead of config
ChristopherRogers1991/mycroft-speedtest pull request #5
Opened 2018-01-19 13:29 UTC by JarbasAl

2018-01-19 15:41 UTC, ChristopherRogers1991 commented
Hey,

Thanks for sending this in. I'm away from home for a couple days, but I'll take a look at this when I'm back home next week.

-Chris

2018-01-20 10:20 UTC, JarbasAI commented
i also added a mark1 animation for the faceplate :)

2018-01-28 04:46 UTC, ChristopherRogers1991 requested changes
Hey @JarbasAl, thanks for submitting this. I think the settings code is basically ready to go (once we remove the default host), but I'd like to iterate more on the animations. If you'd like to split this into two PRs, with the settings and animation separated out, we can probably get the settings portion merged quickly, while we iterate on the animation.

@Sujan4k0 will also be taking a look, so we should have a third opinion soon as well.

-Chris

2018-01-28 04:46 UTC, ChristopherRogers1991 commented on settingsmeta.json
> +                        "value": "speedtest-po.vodafone.pt:8080"
We shouldn't be setting a default value for host; let's set the value to `""` and either remove the placeholder, or set it to something more generic like `hostname:port`.

With no host supplied, the SpeedTest class will find the "best" host (see https://github.com/fopina/pyspeedtest/blob/master/pyspeedtest.py#L67). This is the most familiar and robust behavior (when you go to speedtest.net, it selects the best host, and if the host goes down, our skill won't fail).

2018-01-28 04:46 UTC, ChristopherRogers1991 commented on __init__.py
> +        if self.playing:
This doesn't seem to work as expected. Asking mycroft to stop in the middle of the speedtest doesn't seem to have any effect.

2018-01-28 04:46 UTC, ChristopherRogers1991 commented on __init__.py
> +        if not self.thread:
I think this `handle_speedtest_intent` method is growing a bit too large, and taking on a bit too much. We should extract this `if` block into a function (something like `begin_animation` or `begin_eye_animation`). If you're up for it, lines 228 - 235 (the actual speedtest) could also be extracted into a `run_speedtest` function that returns a tuple with the results. (I like to aggressively refactor, to keep things neat).

2018-01-28 04:46 UTC, ChristopherRogers1991 commented on __init__.py
> +def animate(t, often, func, *args):
I don't think this animation code should live here. This seems like it should be extracted into a utils module/class (and probably as a part of Mycroft core - seems silly to have each skill make it's own animation logic).

2018-01-28 04:46 UTC, ChristopherRogers1991 commented on __init__.py
> +        while self.playing:
Same note here about the animation - I don't think it belongs in this class.

2018-01-28 04:46 UTC, ChristopherRogers1991 commented on __init__.py
> +        if "host" not in self.settings:
I think it would be better to just use `.get(<field>, <default_value>)` in `initialize`, rather than setting these values here.

2018-01-28 05:06 UTC, Sujan4k0 reviewed
Hey, thanks for contributing! Here are some things that I noticed:

2018-01-28 05:06 UTC, Sujan4k0 commented on README.md
> -5. Add the block below to your mycroft.conf file (`~/.mycroft/mycroft.conf`)
This should be kept as the user has two methods to adjust configurations (CLI or UI), so they both should be listed.

2018-01-28 05:06 UTC, Sujan4k0 commented on README.md
> +5. Change skill options in the mycroft.home if desired (requires reboot)
Need correct URL: https://home.mycroft.ai/#/skill

2018-01-28 05:06 UTC, Sujan4k0 commented on README.md
> +  * https://www.speedtest.net/speedtest-servers.php
Should provide context to the link. Right now it looks like it's randomly interjected. 

**Example:**
If you wish to dictate a host for the speedtest in the skill's options, here is a list: https://www.speedtest.net/speedtest-servers.php

2018-01-28 05:06 UTC, Sujan4k0 commented on __init__.py
> +#######################################################################
This commenting style is inconsistent with the rest of the file. In addition, there is no indication of where these helpers end. The divider makes it seem that the section is composed of everything below it.

2018-01-28 05:06 UTC, Sujan4k0 commented on __init__.py
> +def animate(t, often, func, *args):
After checking out the animation...
- Squiggly lines for the mouth while the speedtest is running is a good idea. 
- The eyes flipping up and down don't add anything to the user experience and make it seem buggy when the eyes are half closed and Mycroft is giving the results at the end. I would remove that and keep them static.

2020-09-11 16:26 UTC, closed without merging